name: CI
run-name: ${{ github.actor }}

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, build ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "If you see this message, Congrats"