name: CI
run-name: ${{ github.actor }}

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Build App
        run: pip install -r requirements.txt
      - name: Install lint
        run: python -m flake8 --max-line-length=120 --extend-ignore=F401 src/__init__.py
      - run: echo "If you see this message, Congrats"